import 'dotenv/config';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const firebaseConfig = {
  apiKey: process.env.VITE_FIREBASE_API_KEY || '',
  authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN || '',
  projectId: process.env.VITE_FIREBASE_PROJECT_ID || '',
  messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || '',
  appId: process.env.VITE_FIREBASE_APP_ID || '',
  measurementId: process.env.VITE_FIREBASE_MEASUREMENT_ID || '',
};

const hasConfig = Boolean(
  firebaseConfig.apiKey &&
    firebaseConfig.authDomain &&
    firebaseConfig.projectId &&
    firebaseConfig.messagingSenderId &&
    firebaseConfig.appId
);

const content = `/* Auto-generated by scripts/generate-fcm-sw.ts. Do not edit manually. */

var firebaseConfig = ${JSON.stringify(firebaseConfig, null, 2)};
var hasFirebaseConfig = ${JSON.stringify(hasConfig)};

function safeGetNotificationTitle(payload) {
  if (payload && payload.notification && payload.notification.title) {
    return payload.notification.title;
  }

  if (payload && payload.data && payload.data.title) {
    return payload.data.title;
  }

  return 'TaskBuddy Notification';
}

function safeGetNotificationBody(payload) {
  if (payload && payload.notification && payload.notification.body) {
    return payload.notification.body;
  }

  if (payload && payload.data && payload.data.body) {
    return payload.data.body;
  }

  return '';
}

function safeGetNotificationUrl(payload) {
  if (payload && payload.data && payload.data.url) {
    return payload.data.url;
  }

  return '/TaskBuddy/';
}

try {
  importScripts('https://www.gstatic.com/firebasejs/10.12.5/firebase-app-compat.js');
  importScripts('https://www.gstatic.com/firebasejs/10.12.5/firebase-messaging-compat.js');

  if (hasFirebaseConfig && typeof firebase !== 'undefined') {
    firebase.initializeApp(firebaseConfig);

    var messaging = firebase.messaging();

    messaging.onBackgroundMessage(function (payload) {
      var title = safeGetNotificationTitle(payload);

      var options = {
        body: safeGetNotificationBody(payload),
        icon: '/TaskBuddy/pwa-192x192.png',
        badge: '/TaskBuddy/pwa-192x192.png',
        data: {
          url: safeGetNotificationUrl(payload)
        }
      };

      self.registration.showNotification(title, options);
    });
  } else {
    console.warn('[TaskBuddy SW] Firebase config missing. Background push is disabled.');
  }
} catch (error) {
  console.error('[TaskBuddy SW] Firebase messaging setup failed:', error);
}

self.addEventListener('push', function (event) {
  var payload = {};

  try {
    payload = event.data ? event.data.json() : {};
  } catch (error) {
    payload = {};
  }

  var title = safeGetNotificationTitle(payload);

  var options = {
    body: safeGetNotificationBody(payload),
    icon: '/TaskBuddy/pwa-192x192.png',
    badge: '/TaskBuddy/pwa-192x192.png',
    data: {
      url: safeGetNotificationUrl(payload)
    }
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', function (event) {
  event.notification.close();

  var targetUrl = '/TaskBuddy/';

  if (event.notification && event.notification.data && event.notification.data.url) {
    targetUrl = event.notification.data.url;
  }

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function (clientList) {
      for (var i = 0; i < clientList.length; i += 1) {
        var client = clientList[i];

        if ('focus' in client && client.url.indexOf('/TaskBuddy/') !== -1) {
          if ('navigate' in client) {
            return client.navigate(targetUrl).then(function () {
              return client.focus();
            });
          }

          return client.focus();
        }
      }

      if (clients.openWindow) {
        return clients.openWindow(targetUrl);
      }

      return undefined;
    })
  );
});
`;

mkdirSync(resolve('public'), { recursive: true });
writeFileSync(resolve('public/firebase-messaging-sw.js'), content);
console.log('Generated public/firebase-messaging-sw.js');

if (!hasConfig) {
  console.warn(
    'Warning: Firebase config is incomplete. Check VITE_FIREBASE_API_KEY, VITE_FIREBASE_AUTH_DOMAIN, VITE_FIREBASE_PROJECT_ID, VITE_FIREBASE_MESSAGING_SENDER_ID, and VITE_FIREBASE_APP_ID.'
  );
}
