import 'dotenv/config';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const config = {
  apiKey: process.env.VITE_FIREBASE_API_KEY || '',
  authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN || '',
  projectId: process.env.VITE_FIREBASE_PROJECT_ID || '',
  messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || '',
  appId: process.env.VITE_FIREBASE_APP_ID || '',
  measurementId: process.env.VITE_FIREBASE_MEASUREMENT_ID || '',
};

const hasConfig = Boolean(
  config.apiKey && config.authDomain && config.projectId && config.messagingSenderId && config.appId
);

const content = `/* Auto-generated by scripts/generate-fcm-sw.ts. Do not edit manually. */
importScripts('https://www.gstatic.com/firebasejs/10.12.5/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.12.5/firebase-messaging-compat.js');

const firebaseConfig = ${JSON.stringify(config, null, 2)};

if (${JSON.stringify(hasConfig)}) {
  firebase.initializeApp(firebaseConfig);
  const messaging = firebase.messaging();

  messaging.onBackgroundMessage((payload) => {
    const title = payload.notification?.title || 'TaskBuddy Notification';
    const options = {
      body: payload.notification?.body || '',
      icon: '/TaskBuddy/pwa-192x192.png',
      badge: '/TaskBuddy/pwa-192x192.png',
      data: {
        url: payload.data?.url || '/TaskBuddy/'
      }
    };

    self.registration.showNotification(title, options);
  });
}

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const targetUrl = event.notification?.data?.url || '/TaskBuddy/';

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if ('focus' in client && client.url.includes('/TaskBuddy/')) {
          client.focus();
          if ('navigate' in client) {
            return client.navigate(targetUrl);
          }
          return;
        }
      }

      if (clients.openWindow) {
        return clients.openWindow(targetUrl);
      }
    })
  );
});
`;

mkdirSync(resolve('public'), { recursive: true });
writeFileSync(resolve('public/firebase-messaging-sw.js'), content);
console.log('Generated public/firebase-messaging-sw.js');
